# Generated by Django 6.1 on 2026-09-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='major',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ngành đào tạo'),
        ),
    ]
