# Generated by Django 6.1 on 2026-09-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='candidate_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tên tài khoản ứng viên'),
        ),
    ]
