# Generated by Django 6.1 on 2026-09-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_candidate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cv_skills',
            field=models.TextField(blank=True, null=True, verbose_name='Kỹ năng trích xuất từ CV'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.TextField(blank=True, null=True, verbose_name='Kỹ năng'),
        ),
    ]
