# Generated by Django 6.0.4 on 2026-10-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_cv_skills_alter_profile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recruiter_cv',
            field=models.FileField(blank=True, null=True, upload_to='recruiter_cvs/', verbose_name='CV xác minh nhà tuyển dụng'),
        ),
    ]
