# Generated by Django 6.1 on 2026-09-19 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('email', models.EmailField(max_length=254, verbose_name='Email liên hệ')),
                ('message', models.TextField(verbose_name='Nội dung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian gửi')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Tên công ty')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại liên hệ')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Logo công ty')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ công ty')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website công ty')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Giới thiệu công ty')),
                ('user', models.OneToOneField(limit_choices_to={'is_recruiter': True}, on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản nhà tuyển dụng')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề công việc')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Tên công ty')),
                ('location', models.CharField(max_length=255, verbose_name='Địa điểm')),
                ('salary', models.CharField(max_length=100, verbose_name='Mức lương')),
                ('job_type', models.CharField(max_length=100, verbose_name='Hình thức (Toàn thời gian/Bán thời gian...)')),
                ('description', models.TextField(verbose_name='Mô tả công việc')),
                ('requirements', models.TextField(verbose_name='Yêu cầu ứng viên')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Hạn nộp hồ sơ')),
                ('status', models.CharField(choices=[('Pending', 'Chờ duyệt'), ('Approved', 'Đã duyệt'), ('Rejected', 'Từ chối')], default='Pending', max_length=20, verbose_name='Trạng thái duyệt')),
                ('recruiter', models.ForeignKey(limit_choices_to={'is_recruiter': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nhà tuyển dụng')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_file', models.FileField(upload_to='applications_cvs/', verbose_name='CV ứng tuyển')),
                ('cover_letter', models.TextField(blank=True, verbose_name='Thư giới thiệu')),
                ('status', models.CharField(choices=[('Pending', 'Đang chờ duyệt'), ('Approved', 'Đã duyệt / Phỏng vấn'), ('Rejected', 'Từ chối')], default='Pending', max_length=50, verbose_name='Trạng thái')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview_details', models.TextField(blank=True, null=True, verbose_name='Lịch hẹn và thông tin phỏng vấn trực tiếp')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày nộp')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='Đã gửi email nhắc nhở 24h')),
                ('candidate', models.ForeignKey(limit_choices_to={'is_candidate': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ứng viên')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job', verbose_name='Tin tuyển dụng')),
            ],
        ),
        migrations.CreateModel(
            name='JobChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên người gửi')),
                ('receiver_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên người nhận')),
                ('message', models.TextField(verbose_name='Nội dung tin nhắn')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian gửi')),
                ('is_read', models.BooleanField(default=False, verbose_name='Đã đọc')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='jobs.job', verbose_name='Tin tuyển dụng')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người gửi')),
            ],
        ),
    ]
