# Generated by Django 6.1 on 2026-08-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_details',
            field=models.TextField(blank=True, null=True, verbose_name='Lịch hẹn và thông tin phỏng vấn trực tiếp'),
        ),
    ]
