# Generated by Django 6.1 on 2026-08-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_application_interview_details'),
    ]

    operations = []
