# Generated by Django 6.1 on 2026-08-27 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_expires_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='contact_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Zalo/Group hỗ trợ của công ty'),
        ),
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Nội dung cần hỗ trợ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày gửi')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Đã giải quyết')),
                ('candidate', models.ForeignKey(limit_choices_to={'is_candidate': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ứng viên')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to='jobs.job', verbose_name='Tin tuyển dụng')),
            ],
        ),
    ]
