# Generated by Django 6.1 on 2026-09-05 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_contact_link_supportrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = []
