# Generated by Django 6.1 on 2026-09-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_companyprofile'),
    ]

    operations = []
