# Generated by Django 6.1 on 2026-09-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_companyprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tên công ty'),
        ),
    ]
