# Generated by Django 6.1 on 2026-09-08 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_job_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='contact_link',
        ),
    ]
