# Generated by Django 6.1 on 2026-09-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_remove_job_contact_link'),
    ]

    operations = []
