# Generated by Django 6.1 on 2026-09-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_contactmessage'),
    ]

    operations = []
