# Generated by Django 6.1 on 2026-09-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobchatmessage',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên người nhận'),
        ),
        migrations.AddField(
            model_name='jobchatmessage',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên người gửi'),
        ),
    ]
