# Generated by Django 6.1 on 2026-09-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_contactmessage_is_replied_contactmessage_replied_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Pending', 'Chờ duyệt'), ('Approved', 'Đã duyệt'), ('Rejected', 'Từ chối')], default='Pending', max_length=20, verbose_name='Trạng thái duyệt'),
        ),
    ]
