# Generated by Django 6.1 on 2026-09-17 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_job_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='is_replied',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='replied_at',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='reply_message',
        ),
    ]
