# Generated by Django 6.1 on 2026-09-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_remove_contactmessage_is_replied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='reminder_sent',
            field=models.BooleanField(default=False, verbose_name='Đã gửi email nhắc nhở 24h'),
        ),
        migrations.DeleteModel(
            name='SupportRequest',
        ),
    ]
