# Generated by Django 6.1 on 2026-09-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_application_reminder_sent_delete_supportrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='is_replied',
            field=models.BooleanField(default=False, verbose_name='Đã phản hồi'),
        ),
    ]
