# Generated by Django 6.1 on 2026-09-20 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_contactmessage_is_replied'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên gói cước')),
                ('duration_days', models.IntegerField(verbose_name='Thời hạn (số ngày)')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá tiền (VNĐ)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả quyền lợi gói')),
            ],
        ),
        migrations.CreateModel(
            name='RecruiterAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_posts_left', models.IntegerField(default=1, verbose_name='Số tin miễn phí còn lại')),
                ('package_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày hết hạn gói cước')),
                ('user', models.OneToOneField(limit_choices_to={'is_recruiter': True}, on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_account', to=settings.AUTH_USER_MODEL, verbose_name='Nhà tuyển dụng')),
                ('active_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.subscriptionpackage', verbose_name='Gói cước đang hoạt động')),
            ],
        ),
        migrations.CreateModel(
            name='PackageTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Số tiền thanh toán')),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='payment_proofs/', verbose_name='Ảnh biên lai chuyển khoản')),
                ('status', models.CharField(choices=[('pending', 'Chờ xác nhận thanh toán'), ('approved', 'Đã thanh toán / Kích hoạt'), ('rejected', 'Từ chối')], default='pending', max_length=20, verbose_name='Trạng thái giao dịch')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo giao dịch')),
                ('recruiter', models.ForeignKey(limit_choices_to={'is_recruiter': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nhà tuyển dụng')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.subscriptionpackage', verbose_name='Gói cước đăng ký')),
            ],
        ),
    ]
