# Generated by Django 6.1 on 2026-09-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_subscriptionpackage_recruiteraccount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiteraccount',
            name='posts_remaining',
            field=models.IntegerField(default=0, verbose_name='Số tin còn lại trong gói'),
        ),
        migrations.AddField(
            model_name='subscriptionpackage',
            name='post_limit',
            field=models.IntegerField(default=10, verbose_name='Số lượng tin được phép đăng'),
        ),
    ]
