# Generated by Django 6.1 on 2026-09-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_recruiteraccount_posts_remaining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagetransaction',
            name='package_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tên gói cước'),
        ),
        migrations.AddField(
            model_name='packagetransaction',
            name='recruiter_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tên nhà tuyển dụng'),
        ),
    ]
