# Generated by Django 6.1 on 2026-09-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_packagetransaction_package_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiteraccount',
            name='recruiter_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tên nhà tuyển dụng'),
        ),
    ]
