# Generated by Django 6.1 on 2026-09-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_recruiteraccount_recruiter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='major_required',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ngành yêu cầu'),
        ),
        migrations.AddField(
            model_name='job',
            name='skills_required',
            field=models.TextField(blank=True, null=True, verbose_name='Kỹ năng yêu cầu'),
        ),
    ]
